from community.agents.tableau.research_agent import graph, state, nodes

def initialize_agent():
    """
    TABLEAU RESEARCH AGENT

    This AI Agent writes reports on intelligence aggregated from Tableau in the form of:
        - Metrics (canonical source of truth for metrics, includes machine learning insights generated by Tableau Pulse)
        - Workbooks (contains analytics such as dashboards and charts that server as canonical interfaces for data exploration)
        - Data Sources (describes sources of data available for querying and exploration)
        - Headless BI (can query a data source for on-demand data sets including aggregations, filters and calculations)
        - Web Search (can incorporate external knowledge from the web)

    It is not intended for fluid conversations, rather it takes its time to write thoroughly researched
    summaries of key analytical activity and insights.
    """
    # LangGraph Agents rely on graphs to describe state
    agent = graph.graph_state(state.ResearchAgentState, "research_agent", nodes.chatbot)

    return agent
