from agents.chatbot.graph import graph_state
from agents.chatbot.state import ChatbotState
from agents.chatbot.nodes import chatbot, tools


def initialize_agent(chatbot_store):
    """
    TABLEAU CHATBOT AGENT

    This AI Agent can handle conversations on Tableau subjects such as:
        - Metrics (canonical source of truth for metrics, includes machine learning insights generated by Tableau Pulse)
        - Workbooks (contains analytics such as dashboards and charts that server as canonical interfaces for data exploration)
        - Data Sources (describes sources of data available for querying and exploration)
        - Headless BI (can query a data source for on-demand data sets including aggregations, filters and calculations)
        - Web Search (can incorporate external knowledge from the web)

    Intended to be a simple example of a chatbot inspired by the Langgraph prebuilt `create_react_agent`
    """
    # LangGraph Agents rely on graphs to describe state
    agent = graph_state(
        state_definition=ChatbotState,
        entry_point_name="chatbot",
        entry_point_node=chatbot,
        tool_node=tools,
        store=chatbot_store
    )

    return agent
