from agents.tableau.chatbot import graph, state, nodes

def initialize_agent():
    """
    TABLEAU CHATBOT AGENT

    This AI Agent can handle conversations on Tableau subjects such as:
        - Metrics (canonical source of truth for metrics, includes machine learning insights generated by Tableau Pulse)
        - Workbooks (contains analytics such as dashboards and charts that server as canonical interfaces for data exploration)
        - Data Sources (describes sources of data available for querying and exploration)
        - Headless BI (can query a data source for on-demand data sets including aggregations, filters and calculations)
        - Web Search (can incorporate external knowledge from the web)

    Intended to be a simple example of Chatbot.
    """
    # LangGraph Agents rely on graphs to describe state
    agent = graph.graph_state(state.ChatbotState, "chatbot", nodes.chatbot)

    return agent
